[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

# Force fresh Prisma generation
[[plugins]]
  package = "@netlify/plugin-nextjs"

